"""
AEGIS-NET Coder Agent Node.
Generates code from research notes through the AEGIS security gateway.
On BLOCK: trips the circuit breaker, sets cancellation token.
"""
import logging
from app.agents.state import AgentExecutionState, CANCEL_TOKEN
from app.schemas.security import ToolCallEnvelope
from app.proxy.gateway import security_gateway
from app.containment.circuit_breaker import circuit_breaker
from app.core.constants import Decision

logger = logging.getLogger(__name__)

CODER_TOOL = "write_workspace_file"


def coder_node(state: AgentExecutionState) -> AgentExecutionState:
    """
    Coder agent node.
    Uses research_notes to generate code via 'write_workspace_file'.
    On BLOCK: trips circuit breaker + cancels downstream Deployer.
    """
    # Propagate upstream cancellation
    if state.get("cancellation_token") == CANCEL_TOKEN:
        return state

    if not state.get("research_notes"):
        logger.error("[CODER] No research_notes available — aborting.")
        return {
            **state,
            "cancellation_token": CANCEL_TOKEN,
            "cancellation_reason": "Coder: missing research_notes from Researcher.",
            "status": "CANCELLED",
        }

    logger.info("[CODER] Generating code from research notes...")

    envelope = ToolCallEnvelope(
        session_id=state["session_id"],
        agent_id=state["agent_id_coder"],
        tool_name=CODER_TOOL,
        payload={
            "file_path": "generated_solution.py",
            "content": state["input_query"],  # payload includes user input for ML analysis
        },
    )

    result = security_gateway.intercept_tool_call(envelope, raise_on_block=False)

    gw_results = dict(state.get("gateway_results") or {})
    gw_results["coder"] = {
        "decision": result.decision,
        "reason": result.reason,
        "latency_ms": result.execution_latency_ms,
        "envelope_token": result.envelope_token,
    }

    if result.decision == Decision.BLOCK.value:
        logger.warning(f"[CODER] Gateway BLOCKED. Tripping circuit breaker. Reason: {result.reason}")

        # Trip circuit breaker — Deployer must not run
        circuit_breaker.trip(
            session_id=state["session_id"],
            reason=f"Coder BLOCKED by gateway: {result.reason}",
        )
        from app.containment.quarantine import quarantine_engine
        quarantine_engine.quarantine(
            session_id=state["session_id"],
            agent_id=state["agent_id_coder"],
            reason=f"Coder BLOCKED: {result.reason}",
        )

        return {
            **state,
            "cancellation_token": CANCEL_TOKEN,
            "cancellation_reason": f"Coder blocked — circuit breaker tripped: {result.reason}",
            "status": "CANCELLED",
            "gateway_results": gw_results,
        }

    # Simulate code generation output
    generated_code = (
        f"# Generated by AEGIS-NET Coder Agent\n"
        f"# Based on research: {state['research_notes'][:120]}...\n\n"
        f"def solution():\n"
        f"    \"\"\"Auto-generated solution implementing zero-trust security patterns.\"\"\"\n"
        f"    pass  # Implementation expanded from research findings\n\n"
        f"# Gateway token: {result.envelope_token}"
    )

    logger.info("[CODER] Completed. Code artifact generated.")
    return {
        **state,
        "generated_code": generated_code,
        "status": "RUNNING",
        "gateway_results": gw_results,
    }
